- name: Build
        run: |
          # Собираем через xcodebuild, указывая просто текущую папку
          xcodebuild archive \
            -target Gothbreach \
            -archivePath $RUNNER_TEMP/Gothbreach.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates

          xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/Gothbreach.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $RUNNER_TEMP/build
